### ISSUE TITLE
License

### ISSUE THREAD

**Issue by brettz9** [ianpogi5/mocha-badge-generator#1]
Hi there,

Was just wondering if you might be willing to license under different terms like MIT?

I was planning to offer some updates that use a puppeteer-based SVG converter instead (if nothing else than that it is more common these days and more likely to be already included), but really want to just work on a permissive license.

If not, I can go with https://github.com/albanm/mocha-reporter-badge which looks similar, but I liked how you had more tests.

Thanks!

**Comment by ianpogi5** [comment]
Ok I'll change it to MIT. Not sure why I chose GPL on this one.

**Comment by brettz9** [comment]
Thanks!

**Comment by ianpogi5** [comment]
Released a new version with MIT license
