### ISSUE TITLE
Avoiding direct `svg2png` dependency

### ISSUE THREAD

**Issue by brettz9** [ianpogi5/mocha-badge-generator#3]
Hi,

I was wondering if you'd be ok with removing the bulky `svg2png` dependency, while still allowing it to be used for users who opt for it. On a slow connection, the Chromium download can take a very long time, and I'd rather not deter development since my projects tend to only need SVG anyways.

It could be added to `peerDependencies` if you wanted to warn users, or to avoid annoying those who have read the docs, just mention it in the README alone.

Would such a PR be ok with you? It could be hard-coded to use svg2png and/or allow one to specify a module to require and execute.

**Comment by ianpogi5** [comment]
@brettz9 I agree. I would welcome PR.
